from .utils import (get_score_ahp)

C1_ATTRACTION_COUNT_WEIGHT_DEVELOPER_ATTRACTION = 0.2857
D2_ATTRACTION_COUNT_WEIGHT_DEVELOPER_ATTRACTION = 0.5714

C1_ATTRACTION_COUNT_THRESHOLD_DEVELOPER_ATTRACTION = 1200
D2_ATTRACTION_COUNT_THRESHOLD_DEVELOPER_ATTRACTION = 180

def developer_attraction(item):
    param_dict = {
        "c1_attraction_count": [C1_ATTRACTION_COUNT_WEIGHT_DEVELOPER_ATTRACTION,
                                C1_ATTRACTION_COUNT_THRESHOLD_DEVELOPER_ATTRACTION],
        "d2_attraction_count": [D2_ATTRACTION_COUNT_WEIGHT_DEVELOPER_ATTRACTION,
                                D2_ATTRACTION_COUNT_THRESHOLD_DEVELOPER_ATTRACTION]
    }
    return get_score_ahp(item, param_dict)
